### ISSUE TITLE
Dataset Styles

### ISSUE THREAD

**Issue by userb2020** [creativefloworg/creativeflow#8]
Hello!

Thank you for making this incredible dataset!
I want to use Creative Flow+ for my optical flow research, and I have some questions.

In Figure 7(b) quantitative results (in your CVPR 2019 paper), there are four styles: flat, toon, tex, and stylit.
I downloaded "train_renders_web_halfres.zip (550MB)" and "test_renders_halfres.zip (2.4GB)" on your project page.
I want to categorize these datasets based on those four styles (flat, toon, tex, and stylit).
However, it is hard for me to do that because the file names are not exactly written among the four styles.
For example, I don't know how to classify "style.cpencil2.pencil3.mp4" file.
Could you let me know how to classify your dataset?

I appreciate your consideration!

**Comment by shumash** [comment]
Hi! Thank you for using our data. 

To classify styles, please look at the style image at the bottom of the [README](https://github.com/creativefloworg/creativeflow). The flat style is called "flat", toon shading contains "toon" and all the other shading styles are stylit styles. The naming convention for files is `style.{shading_style_id}.{line_style_id}`. 

You can also use our data readers to filter by the type of style, for example:
```
from creativeflow.blender.dataset_util import DatasetHelper
from creativeflow.blender.dataset_util import ShadingStyles
from creativeflow.blender.dataset_util import DataType

helper = DatasetHelper(
  seq_list_file,
  require_flow=True,
  regex_sources='web|mixamo',
  regex_shading_styles=ShadingStyles.stylit_styles_regex())
```
Please refer to the README on how to use this `helper` to read data, and don't hesitate to reach out with more questions.
